### ISSUE TITLE
Admin - Grid

### ISSUE THREAD

**Issue by JJPietras** [ksobiecki/baUHInia#13]
1. Pola mogą zostać wypełnione literami i innymi znakami niebędącymi cyframi.
2. Wciśnięcie zapisz przy pustych okienkach ceny i wpływu wywala aplikację z siodła.
3. Przy dostatecznie długiej nazwie elementu jego nazwa "chowa się" za ramką grida.
4. Przydały by się drobne paddingi dla elementów UI okna specyfikacji (prawe górne).
5. W przyszłości dodać renderowanie całych obiektów, a nie tylko jednego fragmentu.

**Comment by drzymalski** [comment]
Ej jak robisz issues to fajnie robić takie checkboxy 

- [ ] test123
- [ ] sialalala

**Comment by smiesznypiotrus** [comment]
1. Pola mogą być wypełnione tylko cyframi (jedno ewentualnie kropkami jeszcze)
2. Walidacja w momencie zapisu, pojawia sie messageBox z errorem
3. Nazwa strzyzona do N liter, mozna zmienic w AdminSelectedObjectDetails, tam gdzie sie odwoluje do funkcji shorten(string, int)
4. Dodane paddingi
Na razie wisi commit, ale nie jest zmergowany

**Comment by ksobiecki** [comment]
Fixed
